services:
  web:
    env_file:
      - .env
    image: nenorymusic:1.0.0 
    build: .
    ports:
      - 8000:80
      - 5174:5174
    volumes:
      - .:/var/www/html/
    depends_on:
      - mysql-server
    links:
      - mysql-server
  
  mysql-server:
    env_file: .env
    image: mysql:8.4
    restart: always
    environment:
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD