
name: DEPLOYMENT NENORY INVENTORY APP

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nenory-inventory:${{ github.sha }} .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nenory-inventory:latest .
      - name: login docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USER_TOKEN }}
      - name: docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nenory-inventory:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/nenory-inventory:latest