name: NENORY MUSIC APP

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  laravel-test:
    runs-on: ubuntu-latest
    container:
      image: php:8.2-fpm
 
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    steps:
      - uses: actions/checkout@v2      
      - name: Setup Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 20
          check-latest: true
      - name: Install NPM dependencies
        run: npm install

      - name: Install Vite
        run: npm run build

      - name: Install dependencies for Operative System
        run: |
          apt-get update && apt-get install -y curl libpng-dev libonig-dev libxml2-dev zip unzip 

      - name: Install PHP extensions
        run: |
          docker-php-ext-install pdo pdo_mysql mysqli mbstring exif pcntl bcmath gd
        
      - name: Show php modules
        run: php -m
      
      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install composer dependencies
        run: |
          composer install --optimize-autoloader --no-dev
 
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
      - name: Install phpunit 
        run: composer require --dev phpunit/phpunit
      - name: Run migrate 
        run: php artisan migrate
      - name: Run seeds
        run: php artisan db:seed
